[package]
name = "seafrepo"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.35", features = ["zlib"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
walkdir = "2"
